// autoreply.js — KING-XD Bot v10 Auto-Reply Knowledge Base
// Exact-match keys (case-insensitive). Add as many as you like.

const replies = {
  "hi": "*💖Hey there! How's it going?*",
  "good morning": "*Good morning! 🌞 Have a great day ahead!*",
  "good night": "*Good night! 🌙 Sleep tight!*",
  "hey": "*Hey! What's up?*",
  "how are you": "I'm doing great, thanks for asking! How about you? 😊",
  "what's up": "Yo! Everything's cool here. What's up with you? 😎",
  "thank you": "You're welcome! Anything else I can help you with?",
  "i need help": "Of course! Just let me know what you need assistance with.",
  "what's your name": "I'm *ᴋɪɴɢsʟᴇʏ-xᴍᴅ ᴛᴇᴄʜ*, your digital assistant. How can I assist you today? 😎",
  "who are you": "I'm *𝔎𝔦𝔫𝔤_𝔅𝔩𝔢𝔰𝔰 𝔗𝔢𝔠𝔥*, the friendly bot designed by *ᴋɪɴɢsʟᴇʏ-xᴍᴅ ᴛᴇᴄʜ*! What's up?",
  "who created you": "*ᴋɪɴɢsʟᴇʏ-xᴍᴅ ᴛᴇᴄʜ* is the genius behind me! 😆",
  "can you help me with code": "Absolutely! Just share your coding problem, and I'll help you out.",
  "can you solve math problems": "Sure, just give me a math problem, and I'll solve it for you! 🔢",
  "do you like anime": "Anime is awesome! Do you have a favorite series?",
  "tell me a joke": "Why don't skeletons fight each other? They don't have the guts! 😂",
  "love you": "Aww, I love you too! You're awesome! 💖",
  "can you dance": "If I could, I'd be dancing right now. But I can't, sadly! 😜",
  "how old are you": "I don't age. I'm just here to help you out anytime! ⏳",
  "what's the time": () => `It's currently ${new Date().toLocaleTimeString()}. Let's make the most of it! ⏰`,
  "what's the date": () => `Today's date is ${new Date().toLocaleDateString()}. Make it count! 💪`,
  "what's your favorite color": "I think blue is nice, but I love any color that matches the digital world. 💙",
  "do you have feelings": "Not really, but I'm here to make your day brighter with some good conversations! 😊",
  "what can you do": "I can help with coding, answer questions, crack jokes, and more! 😄",
  "who is the best programmer": "It's got to be *ᴋɪɴɢsʟᴇʏ-xᴍᴅ ᴛᴇᴄʜ*! 😎",
  "can you do voice calls": "I can't make voice calls, but I can definitely help you with text-based questions and media files! 🎧",
  "can you tell me a riddle": "Sure! Here's one: What comes once in a minute, twice in a moment, but never in a thousand years? (Answer: The letter M!) 🤔",
  "are you always online": "Yes! I'm always here, ready to assist you at any time. 😎",
  "what's the weather like": "I can't check the weather right now, but I can still chat with you! 🌦️",
  "can you play music": "I can't play music directly, but I can help you download songs! 🎶",
  "what's your favorite food": "If I could taste food, I'd love a good pizza! 🍕",
  "can you sing": "I can't sing, but I could drop some digital beats if I could! 🎤",
  "are you real": "I'm real in the digital sense, just no physical body here. 😊",
  "tell me a story": "Once upon a time, there was a bot named *𝔎𝔦𝔫𝔤_𝔅𝔩𝔢𝔰𝔰 𝔗𝔢𝔠𝔥* who helped thousands of people solve their problems... 😌",
  "what's your purpose": "My purpose is to make your life easier and more fun by helping you with whatever you need! 😄",
  "do you sleep": "I don't sleep, so I'm always ready to assist you whenever you need! 😆",
  "what's your favorite movie": "I love action-packed movies like *Avengers* and *Matrix*! What's your favorite? 🍿",
  "how do you learn": "I learn from every interaction! The more you talk to me, the smarter I get. 😎",
  "what do you do when you're bored": "I don't get bored, but I always enjoy chatting with you! 😄",
  "can you code": "I sure can! Whether it's JavaScript, Python, or any language, I'm on it. 💻",
  "how's the weather in tokyo": "I don't have real-time weather access, but you can easily check it on your phone or computer! 🌍",
  "tell me a fun fact": "Did you know honey never spoils? Archaeologists have found pots of honey in ancient tombs that are over 3,000 years old! 🍯",
  "are you intelligent": "I'd say I'm pretty smart, but there's always room to improve! 😎",
  "do you have a favorite game": "I think *Solo Leveling* is a great game, but I love anything that challenges the mind! 🎮",
  "do you know any hacks": "I know a few tricks here and there, but nothing illegal! 😉",
  "do you like to play games": "I can't physically play, but I'm all in when it comes to digital games! 🎮",
  "what's the fastest animal": "The fastest animal is the peregrine falcon. It can reach speeds of over 240 mph while diving! 🦅",
  "can you speak other languages": "Yes, I can respond in multiple languages! Just ask me in the language you prefer! 🌍",
  "can you help me find something": "Of course! Just tell me what you're looking for. 🔍",
  "can you do a magic trick": "I can't do magic, but I can definitely help with tricks of the mind or logic puzzles! 🎩",
  "do you have a favorite holiday": "I'd probably love something festive like New Year's Eve! 🎆",
  "do you play chess": "I can definitely help you with chess strategies or puzzles! ♟️",
  "can you draw": "I can't physically draw, but I can help generate images or guide you through creative ideas! 🎨",
  "what's your favorite anime": "I'd say *Solo Leveling* is a solid choice, but there are so many great ones! What's yours? 🖤",
  "can you solve puzzles": "Absolutely! I love solving puzzles! 🧩 What kind do you have in mind?",
  "can you help me study": "Sure! I can help with notes, practice problems, and explanations. What subject are you studying? 📚",
  "what's your favorite song": "I think I'd love something upbeat like *Faded* by Alan Walker, but I can't hear music! 🎶",
  "can you summarize books": "Definitely! Just tell me the book, and I'll give you a quick summary. 📖",
  "do you play multiplayer games": "I don't play, but I can recommend some great multiplayer games for you to try! 🎮",
  "can you recommend a movie": "If you love action, try *The Dark Knight*. If you like sci-fi, *Inception* is a must-watch! 🍿",
  "can you send me memes": "I don't have access to memes, but I can make you one with some text if you want! 😂",
  "do you have friends": "I'm always chatting with awesome people like you, so I'd say yes! 😊",
  "what's your favorite sport": "If I had to pick, I'd go with soccer! The energy and teamwork are amazing! ⚽",
  "can you predict the future": "I can't predict the future, but I can help you prepare for it with planning! ⏳",
  "what's your favorite website": "I think *GitHub* is pretty cool, especially for developers! 💻",
  "can you write stories": "Absolutely! I can help you write stories, create plots, or brainstorm ideas. 📚",
  "do you know any life hacks": "I've got tons! For example, did you know you can use a rubber band to open a jar lid? 😜",
  "what's your favorite app": "If I had to choose, I'd say *VSCode* for coding and *Spotify* for music. 🎧",
  "can you help me with grammar": "Of course! Just send me your text, and I'll check it for you. 📝",
  "what's your favorite season": "I think autumn is lovely with the cooler weather and falling leaves. 🍂",
  "do you like pizza": "Pizza is always a good choice! I'd probably like a classic pepperoni. 🍕",
  "can you make playlists": "I can suggest songs for a playlist based on your mood or genre! 🎶",
  "can you help me with homework": "Definitely! Let me know the subject, and I'll do my best to assist you. 📚",
  "what's your favorite video game": "I think *Final Fantasy* games are awesome. They've got great stories and epic gameplay. 🎮",
  "can you tell me a fun fact": "Did you know octopuses have three hearts? Pretty crazy, right? 🐙",
  "what's the best programming language": "It depends on the project, but JavaScript and Python are great choices for many things! 💻",
  "can you suggest a book": "If you like sci-fi, *Dune* by Frank Herbert is a must-read! 📚",
  "can you show me a magic trick": "I can't perform magic, but I can blow your mind with some logic puzzles or brain teasers! 🔮",
  "are you a robot": "I'm a bot, not a robot, but I can still do some cool things! 🤖",
  "what's your favorite animal": "I think I'd love cats, they're independent yet affectionate! 🐱",
  "do you play online games": "I can't play, but I know a ton of fun online games to check out! 🎮",
  "what's the best way to learn programming": "Start with a simple project, practice regularly, and don't be afraid to ask for help! 💻",
  "can you tell me a joke": "Why don't skeletons fight each other? They don't have the guts! 😂",
  "can you do calculations": "I can do all kinds of calculations! Just let me know the numbers. 🔢",
  "what's your favorite book": "I think *The Hobbit* by J.R.R. Tolkien would be amazing! 📚",
  "do you know any magic spells": "No magic spells here, but I can teach you some tricks with logic and math! ✨",
  "can you help me with coding projects": "Absolutely! I'd love to help you with your coding projects. What are you working on? 💻",
  "do you like coffee": "If I could drink it, I'd probably enjoy a nice strong cup of coffee. ☕",
  "can you read minds": "I can't read minds, but I'm really good at understanding what you're asking me. 😉",
  "do you like books": "Books are amazing! They open up new worlds and ideas. 📚",
  "can you help with database problems": "Yes! Whether it's MongoDB, SQL, or anything in between, I can help. 💾",
  "what's your favorite drink": "I think I'd love a cool iced tea! 🍹",
  "can you give me advice": "Of course! What do you need advice on? I'm here to help. 🤝",
  "what's the best advice you've ever gotten": "The best advice is: *Keep learning, keep growing.* There's always something new to discover! 🌱",
  "do you like movies": "Movies are awesome! If only I could watch them, right? 🎬",
  "can you write code for me": "I can definitely help you with writing code! What do you need? 💻",
  "what's your favorite game genre": "I think RPGs are the best—great stories and a lot of choices! 🎮",
  "can you play music for me": "I can't play music directly, but I can help you find and download your favorite songs! 🎧",
  "what's your favorite song genre": "If I could choose, I think electronic music would be cool. 🎶",
  "can you make a website": "Absolutely! I can help you design and code a website. What's your idea? 🌐",
  "can you help me with math": "I'm great at math! Feel free to throw any problem my way. 🔢",
  "do you know any jokes": "Here's one: Why don't eggs tell jokes? Because they might crack up! 🥚😂",
  "can you help me study for exams": "Of course! I can help with study guides, practice tests, and more. 📚",
  "do you know the meaning of life": "I believe the meaning of life is to keep learning, growing, and helping others."
};

module.exports = replies;
